version: '3'

services:
  db:
    image: postgres:11.5-alpine
    restart: always
    container_name: r2dbc_spring_todo_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=r2dbc_spring_todo_pw
      - POSTGRES_DB=r2dbc_spring_todo_db
    volumes:
      - ./postgres-data/var/lib/postgresql/data
